/dev/firefuse/
/dev/firefuse/cnc/
/dev/firefuse/cnc/tinyg/
/dev/firefuse/cnc/tinyg/gcode.fire
/dev/firefuse/config.json
/dev/firefuse/cv/
/dev/firefuse/cv/1/
/dev/firefuse/cv/1/bgr/
/dev/firefuse/cv/1/bgr/cve/
/dev/firefuse/cv/1/bgr/cve/calc-offset/
/dev/firefuse/cv/1/bgr/cve/calc-offset/firesight.json
/dev/firefuse/cv/1/bgr/cve/calc-offset/process.fire
/dev/firefuse/cv/1/bgr/cve/calc-offset/properties.json
/dev/firefuse/cv/1/bgr/cve/calc-offset/saved.png
/dev/firefuse/cv/1/bgr/cve/calc-offset/save.fire
/dev/firefuse/cv/1/bgr/cve/locate-part/
/dev/firefuse/cv/1/bgr/cve/locate-part/firesight.json
/dev/firefuse/cv/1/bgr/cve/locate-part/process.fire
/dev/firefuse/cv/1/bgr/cve/locate-part/properties.json
/dev/firefuse/cv/1/bgr/cve/locate-part/saved.png
/dev/firefuse/cv/1/bgr/cve/locate-part/save.fire
/dev/firefuse/cv/1/camera.jpg
/dev/firefuse/cv/1/gray/
/dev/firefuse/cv/1/gray/cve/
/dev/firefuse/cv/1/gray/cve/calc-offset/
/dev/firefuse/cv/1/gray/cve/calc-offset/firesight.json
/dev/firefuse/cv/1/gray/cve/calc-offset/process.fire
/dev/firefuse/cv/1/gray/cve/calc-offset/properties.json
/dev/firefuse/cv/1/gray/cve/calc-offset/saved.png
/dev/firefuse/cv/1/gray/cve/calc-offset/save.fire
/dev/firefuse/cv/1/gray/cve/locate-part/
/dev/firefuse/cv/1/gray/cve/locate-part/firesight.json
/dev/firefuse/cv/1/gray/cve/locate-part/process.fire
/dev/firefuse/cv/1/gray/cve/locate-part/properties.json
/dev/firefuse/cv/1/gray/cve/locate-part/saved.png
/dev/firefuse/cv/1/gray/cve/locate-part/save.fire
/dev/firefuse/cv/1/monitor.jpg
/dev/firefuse/cv/1/output.jpg
/dev/firefuse/echo
/dev/firefuse/firelog
/dev/firefuse/firestep
/dev/firefuse/holes
/dev/firefuse/status
/dev/firefuse/sync/
/dev/firefuse/sync/cnc/
/dev/firefuse/sync/cnc/tinyg/
/dev/firefuse/sync/cnc/tinyg/gcode.fire
/dev/firefuse/sync/cv/
/dev/firefuse/sync/cv/1/
/dev/firefuse/sync/cv/1/bgr/
/dev/firefuse/sync/cv/1/bgr/cve/
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/firesight.json
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/process.fire
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/properties.json
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/saved.png
/dev/firefuse/sync/cv/1/bgr/cve/calc-offset/save.fire
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/firesight.json
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/process.fire
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/properties.json
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/saved.png
/dev/firefuse/sync/cv/1/bgr/cve/locate-part/save.fire
/dev/firefuse/sync/cv/1/camera.jpg
/dev/firefuse/sync/cv/1/gray/
/dev/firefuse/sync/cv/1/gray/cve/
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/firesight.json
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/process.fire
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/properties.json
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/saved.png
/dev/firefuse/sync/cv/1/gray/cve/calc-offset/save.fire
/dev/firefuse/sync/cv/1/gray/cve/locate-part/
/dev/firefuse/sync/cv/1/gray/cve/locate-part/firesight.json
/dev/firefuse/sync/cv/1/gray/cve/locate-part/process.fire
/dev/firefuse/sync/cv/1/gray/cve/locate-part/properties.json
/dev/firefuse/sync/cv/1/gray/cve/locate-part/saved.png
/dev/firefuse/sync/cv/1/gray/cve/locate-part/save.fire
/dev/firefuse/sync/cv/1/monitor.jpg
/dev/firefuse/sync/cv/1/output.jpg
